@startuml 演習３－５
left to right direction
object ホテル {
部屋
}
object "<u>301号室: 部屋</u>" as h1 {
タイプ=シングル
価格=11,000円
キャンペーン価格=9,000円
}
object "<u>302号室: 部屋</u>" as h2 {
タイプ
価格
キャンペーン価格
}
object "<u>303号室: 部屋</u>" as h3 {
タイプ=シングル
価格=11,000円
キャンペーン価格=9,000円
}
ホテル -- h1
ホテル -- h2
ホテル -- h3
@enduml