@startuml 演習4-5_商品情報検索
hide footbox
Actor "<u>:会員</u>" as member
participant ":商品検索画面" as search <<boundary>>
participant ":商品検索コントローラ" as control  <<control>>
activate member
    member -> search:注文情報を確認
    activate search
        search -> control:商品情報表示
        activate control
            create "<u>:商品</u>" as goods <<entity>>
            control --> goods:<<create>>生成()
            create "<u>:商品カテゴリ</u>" as category <<entity>>
            loop  商品カテゴリ
            control --> category:<<create>>生成()
            control -> goods:商品カテゴリを設定
            activate goods
            deactivate goods
            end
            search <-- control:商品情報
            deactivate control
            search -> search:商品情報表示
            activate search
@enduml