@startuml 盛岡システム（株）
    ' left to right direction
    actor 社員 as d
    actor 人事担当者 as a #DDDDDD;line:black;line.bold;
    rectangle 従業員登録システム {
    usecase 従業員登録する as b
    usecase 社員情報を参照する as c
    usecase 社員情報を変更する as e
    }
    a --> b
    d --> c
    a --> e
@enduml