@startuml 演習６－３
[*] -right-> メニュー
メニュー --> 予約と確認 : 登録
メニュー <-right- 予約と確認 : 取り消し
メニュー <-- あなたの順番 : 登録者番号の表示
メニュー --> 今の順番 : 今の患者の順番を表示
メニュー <-right- 今の順番 : 患者の番号を1つ増やす
予約と確認 -right-> あなたの順番 : 登録ボタンを押す
予約と確認 -right-> あなたの順番 : 確認ボタンを押す
メニュー -right-> [*]
@enduml