@startuml 演習６－３
' left to right direction
state 診察予約システム {
    [*] -right--> メニュー画面 : 接続ON
    メニュー画面 -down--> 予約と確認画面  : 予約
    予約と確認画面 -up--> メニュー画面 : 取り消しボタンを押す
    予約と確認画面 -right--> あなたの順番画面 : 登録ボタンを押す
    予約と確認画面 -right--> あなたの順番画面 : 確認ボタンを押す
    あなたの順番画面 -up--> メニュー画面 : メニューボタンを押す
    今の順番画面 -up--> メニュー画面 : メニューボタンを押す
    メニュー画面 -down--> 今の順番画面 : 今の順番ボタンを押す
    メニュー画面 -right--> [*] : 接続OFF
}
@enduml