@startuml 演習６－３
left to right direction
actor 患者 as user#DDDDDD;line:black;line.bold;
actor 看護師 as kango#DDDDDD;line:black;line.bold;
rectangle 診察予約システム {
    usecase メニュー
    usecase 予約と確認
    usecase あなたの順番
    usecase 今の順番
}
user --> メニュー
user --> 予約と確認
user --> あなたの順番
user --> 今の順番
今の順番 <-- kango
@enduml