@startuml 演習３－４ オブジェクト図
left to right direction
object "<u>車1: 車</u>" as k1 {
ID=1
車種=プリウス
車メーカー=ホンダ
}
object "<u>タイヤ情報1: タイヤ</u>" as t1 {
種類=サマータイヤ
タイヤメーカー=ブリヂストン
車ID=1
}
object "<u>タイヤ情報2: タイヤ</u>" as t2 {
種類=サマータイヤ
タイヤメーカー=ブリヂストン
車ID=1
}
object "<u>タイヤ情報3: タイヤ</u>" as t3 {
種類=サマータイヤ
タイヤメーカー=ブリヂストン
車ID=1
}
object "<u>タイヤ情報4: タイヤ</u>" as t4 {
種類=サマータイヤ
タイヤメーカー=ブリヂストン
車ID=1
}
k1 -- t1
k1 -- t2
k1 -- t3
k1 -- t4
@enduml